# Generated by Django 5.1.1 on 2024-09-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_counter',
            field=models.PositiveBigIntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='Счётчик просмотров'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/photo', verbose_name='Изображение'),
        ),
    ]
