# Generated by Django 5.1.1 on 2024-09-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_views_counter_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveBigIntegerField(default=1, verbose_name='номер версии')),
                ('name', models.CharField(max_length=255, verbose_name='Название Версии')),
                ('indicates_the_current_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_products', to='catalog.category', verbose_name='Признаки Текущей Версии')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='catalog.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Product parent',
                'verbose_name_plural': 'Products',
                'ordering': ['indicates_the_current_version', 'name'],
            },
        ),
    ]
